
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: '{{doc("table_events")}}'
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: custom_model
      description: 'this is custom model'
      columns:
      - name: id
        description: '{{ doc("custom_model_id") }}'
      - name: name
        description: '{{ doc("custom_model_name") }} '
      - name: age
        description:  '{{ doc("custom_model_age") }}'